### ISSUE TITLE
Wrong phone-number displaying in Slack integration

### ISSUE THREAD

**Issue by jmgaya** [tuenti/simtron#1]
### Current behaviour

Some *phone numbers* are displayed with the "international" formatting, which causes people to copy+paste them into the OB login directly, which ends up failing.

### Expected behaviour

We should be able to "choose" how the number is formatted/displayed in Slack.

### Examples

```
59893746054 => 093746054
59893583808 => 093583808
```

**Comment by wyunreal** [comment]
done !
